export const companyLink: string;
export const content: string;
export const contentPara: string;
export const heading: string;
export const name: string;
export const page: string;
export const section: string;
export const subHeading: string;
export const testimonialLink: string;
